use shop;
SELECT * FROM category;
SELECT * FROM category WHERE id = 3;
SELECT * FROM category WHERE discount <> 0;
SELECT * FROM category WHERE discount > 5;
SELECT * FROM category WHERE (discount > 5) AND (discount < 15);
SELECT * FROM category WHERE (discount < 5) OR (discount >= 10);
SELECT * FROM category WHERE NOT (discount < 5);
SELECT * FROM category WHERE alias_name IS NOT NULL;
SELECT * FROM category WHERE alias_name IS NULL;
SELECT * FROM good_type WHERE type = 'Платье';